DROP TABLE LAS2PEERMON.MESSAGE,LAS2PEERMON.AGENT,LAS2PEERMON.REGISTERED_AT,LAS2PEERMON.NODE,LAS2PEERMON.SERVICE;

CREATE TABLE LAS2PEERMON.MESSAGE (
	ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
	EVENT VARCHAR(255) NOT NULL,
	TIME_STAMP BIGINT NOT NULL,
	SOURCE_NODE VARCHAR(255),
	SOURCE_AGENT BIGINT,
	DESTINATION_NODE VARCHAR(255),
	DESTINATION_AGENT BIGINT,
	REMARKS VARCHAR(255),
	CONSTRAINT MESSAGE_PK PRIMARY KEY (ID),
	CONSTRAINT SOURCE_NODE_FK FOREIGN KEY (SOURCE_NODE) REFERENCES LAS2PEERMON.NODE(NODE_ID),
	CONSTRAINT DESTINATION_NODE_FK FOREIGN KEY (DESTINATION_NODE) REFERENCES LAS2PEERMON.NODE(NODE_ID),
	CONSTRAINT SOURCE_AGENT_FK FOREIGN KEY (SOURCE_AGENT) REFERENCES LAS2PEERMON.AGENT(AGENT_ID),
	CONSTRAINT DESTINATION_AGENT_FK FOREIGN KEY (DESTINATION_AGENT) REFERENCES LAS2PEERMON.AGENT(AGENT_ID)
);


CREATE TABLE LAS2PEERMON.AGENT (
	AGENT_ID BIGINT NOT NULL,
	TYPE varchar(255) NOT NULL,
  	CHECK (TYPE IN ('USER', 'SERVICE', 'GROUP', 'MONITORING', 'MEDIATOR')),
	CONSTRAINT AGENT_PK PRIMARY KEY (AGENT_ID)
);


CREATE TABLE LAS2PEERMON.REGISTERED_AT (
	REGISTRATION_DATE TIMESTAMP,
	UNREGISTRATION_DATE TIMESTAMP,
	AGENT_ID BIGINT NOT NULL,
	RUNNING_AT VARCHAR(255),
	CONSTRAINT AGENT_ID_FK FOREIGN KEY (AGENT_ID) REFERENCES LAS2PEERMON.AGENT(AGENT_ID),
	CONSTRAINT RUNNING_AT_FK FOREIGN KEY (RUNNING_AT) REFERENCES LAS2PEERMON.NODE(NODE_ID)
);


CREATE TABLE LAS2PEERMON.NODE (
	NODE_ID VARCHAR(255) NOT NULL,
	NODE_LOCATION VARCHAR(255) NOT NULL,
	CONSTRAINT NODE_PK PRIMARY KEY (NODE_ID)
);


CREATE TABLE LAS2PEERMON.SERVICE (
	AGENT_ID BIGINT NOT NULL,
	SERVICE_CLASS_NAME VARCHAR(255) NOT NULL,
	CONSTRAINT SERVICE_PK PRIMARY KEY (AGENT_ID),
	CONSTRAINT SERVICE_FK FOREIGN KEY (AGENT_ID) REFERENCES LAS2PEERMON.AGENT(AGENT_ID),
	CONSTRAINT SERVICE_UK UNIQUE (AGENT_ID,SERVICE_CLASS_NAME)
);